name: CI

on:
  push:
    branches: [master]
  workflow_dispatch:
  repository_dispatch:

jobs:
  trigger-site-repo-workflow:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
    steps:
    - run: gh workflow run main.yml --ref master --repo haxeflixel/haxeflixel.com
      env:
        GH_TOKEN: ${{ github.token }}
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: lix-pm/setup-lix@master
    - uses: ninjamuffin99/setup-flixel@master
      with:
        haxe-version: 4.3.2
        flixel-versions: release
        target: flash
    - run: npm install
      working-directory: api/dox
    - run: haxe --cwd api --run Make xml pages
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        publish_dir: ./api/dox/out
        cname: api.haxeflixel.com
